# Generated by Django 4.2 on 2024-08-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='avatares/default_avatar.svg', null=True, upload_to='avatares'),
        ),
    ]
