# Generated by Django 4.2 on 2024-09-04 02:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='avatares/default_avatar.svg', null=True, upload_to=users.models.get_random_filename),
        ),
    ]
