# Generated by Django 4.2 on 2024-08-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='blogs_imgs/default_blog_img.jpg', null=True, upload_to='blogs_imgs')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='blogs.blogs')),
            ],
        ),
    ]
